import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import profile from '../public/me.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gradient-to-b from-gray-900 to-blue-900 min-h-screen'>
        <div className='w-screen grid place-items-center'>

            <Image className='rounded-full w-80' src={profile} alt='Joatan Sampaio'></Image>
            <h1 className='py-7 text-center text-5xl'>Joatan Sampaio</h1>
        </div>
      </main>

    </div>
  )
}
