import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import FloatingBall from '../components/FloatingBall'
import NavBar from '../components/NavBar'
import profile from '../public/me2.png'
import ContentPaper from '../components/ContentPaper'
import Profile from '../components/Profile'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gradient-to-tl from-j_main_dark to-j_main_light min-h-screen'>
        <div className='pt-10 w-11/12 md:w-5/6 xl:w-4/6 m-auto '>
          <NavBar />
          <div id="profile-logo" className='absolute top-40 md:top-52 mb-16 left-1/2 -translate-x-1/2'>
            
            <Profile />

            <FloatingBall attr="animate-circ0 before:content-html" />
            <FloatingBall attr="animate-circ45 before:content-css" />
            <FloatingBall attr="animate-circ90 before:content-java" />
            <FloatingBall attr="animate-circ180 before:content-javascript" />
            <FloatingBall attr="animate-circ270 before:content-react" />

          </div>
          <section className='mt-72 mx-6 md:mt-100'>
              <h1 className='py-10 font-extralight text-center text-4xl md:py-16'>Joatan Sampaio</h1>
              <p>
                In love with computers since 2003 when I was only 13 years old, I've had many upside downs in this area.
                I always loved programming! My first programming language was C back in 2005 and I kept programming for at lest 2 years.
                Most of my projects were game-related macros in C to get ahead of other players. Also, back then I worked a little bit with HTML and CSS
                to create 2 or 3 websites; one of which I actually sold to a security camera company.
              </p>
              <br />
              <p>
                Many years later, in 2012, I got back to programming! This time, with Java. I got to learn a lot and managed to get a certification
                in java. Soon later that, I started to attend College, where I porsued a bachelor's degree in Systems of Information, which is a computer science related program.
              </p>
              <br />
              <p>
                Unfortunatelly, I never got to the end of this one. Actually, I gave up on it at the beginning of my 4th year. The reason behind that is that I
                started singing and playing, I made a good living out it for many years. In reality when I got into College, I was already working with that for 1 or 2 years.
              </p>
          </section>
          <section>
            Projects
          </section>
          <section>
            Skills
          </section>
          <section className=''>
            Contact
          </section>
        </div>
      </main>

    </div>
  )
}
